<a href="https://colab.research.google.com/github/IlyaZutler/Project_2-Trucks/blob/main/Basic_ML_Project_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#

# Project guidelines - Heavy Machinery Auction Price Estimator - ML Project Documentation

> https://www.kaggle.com/t/9baafb8850d74e4499c7b1ba97d6f115

## Overview

Welcome to the Heavy Machinery Auction Price Estimator competition! This document will guide you through the steps required to participate in the competition, including setting up your environment, understanding the dataset, building your model, and submitting your predictions.

### Goal
The objective of this competition is to develop a model that accurately estimates the final sale price of heavy machinery based on historical auction data. This will help create a reliable pricing guide for heavy machinery.

### Timeline
- **Start Date:** [Start Date]
- **End Date:** 14/07/2024 (11 days to go)

## Dataset Description

The dataset consists of historical sales data of heavy machinery. It includes detailed information such as manufacturing year, usage hours, and various machine configurations.

### Files
- `train.csv`: Contains the training data with features and the target variable (`SalePrice`).
- `valid.csv`: Contains the validation data with features but without the `SalePrice` column. This is used to generate predictions for submission.

### Data Columns
- `SalesID`: Unique identifier for each sale.
- `SalePrice`: The target variable, representing the final sale price of the machinery.
- `YearMade`: The year the machinery was manufactured.
- `MachineHoursCurrentMeter`: The usage hours of the machinery.
- Other columns representing various machine configurations and features.

## Evaluation Metric

Submissions will be evaluated using the Root Mean Squared Error (RMSE) metric, which measures the average magnitude of the errors between the predicted and actual auction sale prices. The formula for RMSE is:

\[ \text{RMSE} = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2} \]

Where \( y_i \) is the actual sale price and \( \hat{y}_i \) is the predicted sale price.

## Submission File

Your submission file should be a CSV file with two columns: `SalesID` and `SalePrice`. The file should include a header and be formatted as follows:

```
SalesID,SalePrice
1,10000
2,15000
...
```

Ensure that your submission file includes all IDs from the validation set and follows the specified format to be successfully scored.

## Getting Started

### 1. Environment Setup

Set up your Python environment with the necessary libraries:

```bash
pip install pandas numpy scikit-learn
```

### 2. Exploratory Data Analysis (EDA)

Conduct EDA to understand the dataset and identify any data quality issues. Look for missing values, outliers, and relationships between features and the target variable.

### 3. Data Preprocessing

- Handle missing values appropriately.
- Encode categorical variables.
- Normalize or standardize numerical features if necessary.

### 4. Baseline Model

Start with a baseline model to establish a benchmark performance. A simple approach is to predict the mean of the target variable:

```python
import pandas as pd

train = pd.read_csv('train.csv')
baseline_prediction = train['SalePrice'].mean()

# Create a submission file
valid = pd.read_csv('valid.csv')
submission = pd.DataFrame({'SalesID': valid['SalesID'], 'SalePrice': baseline_prediction})
submission.to_csv('baseline_submission.csv', index=False)
```

### 5. RandomForestRegressor Model

Build a RandomForestRegressor model:

```python
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import numpy as np

# Split the data
X = train.drop(columns=['SalePrice'])
y = train['SalePrice']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Validate the model
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f'RMSE: {rmse}')
```

### 6. Model Improvement

- Handle missing values and categorical variables more effectively.
- Use feature importances to identify key features.
- Perform feature engineering to create new informative features.
- Tune hyperparameters using grid search or other techniques.
- Monitor for overfitting by comparing training and testing performance.

### 7. Final Submission

Generate predictions for the validation set:

```python
valid = pd.read_csv('valid.csv')
X_valid = valid.drop(columns=['SalesID'])
y_valid_pred = model.predict(X_valid)

# Create a submission file
submission = pd.DataFrame({'SalesID': valid['SalesID'], 'SalePrice': y_valid_pred})
submission.to_csv('final_submission.csv', index=False)
```

## Practical Data Science Guidelines

- **Efficient Workflows:** Use a random subset of 20,000 rows for initial experiments. Use the full dataset for the final submission.
- **Iterative Approach:** Start with a basic model and iteratively improve it by trying small ideas.
- **Feature Engineering:** Transform and combine existing features creatively.
- **Documentation:** Keep track of your experiments and results. Document what works and what doesn't.

## Collaboration and Presentation

- **Collaboration:** Discuss your work openly within your team or with other teams. Sharing insights and learning from each other is encouraged.
- **Presentation:** Present your methodology, results, and the techniques that helped the most. Document your journey and the steps you took to achieve your results.

## Have Fun!

Enjoy the process of learning and competing. This is an opportunity to improve your skills and collaborate with others.

Good luck in the competition!

# ok lets get started!

In [1]:
import gdown
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from pathlib import Path

def download_from_gdrive(url, filename):
    # Extract the file ID from the URL
    file_id = url.split('/')[-2]
    download_url = f"https://drive.google.com/uc?id={file_id}"

    # Download the file
    if Path(filename).exists():
        print(f"File '{filename}' already exists. Skipping download.")
    else:
        gdown.download(download_url, filename, quiet=False)
        print(f"File downloaded as: {filename}")

train = 'https://drive.google.com/file/d/1guqSpDv1Q7ZZjSbXMYGbrTvGns0VCyU5/view?usp=drive_link'
valid = 'https://drive.google.com/file/d/1j7x8xhMimKbvW62D-XeDfuRyj9ia636q/view?usp=drive_link'
# Example usage

download_from_gdrive(train, 'train.csv')
download_from_gdrive(valid, 'valid.csv')

df = pd.read_csv('train.csv')
df.head()

Downloading...
From (original): https://drive.google.com/uc?id=1guqSpDv1Q7ZZjSbXMYGbrTvGns0VCyU5
From (redirected): https://drive.google.com/uc?id=1guqSpDv1Q7ZZjSbXMYGbrTvGns0VCyU5&confirm=t&uuid=de3b5f4c-7e97-48ec-87ff-7656154e2993
To: /content/train.csv
100%|██████████| 116M/116M [00:02<00:00, 53.2MB/s]

File downloaded as: train.csv

Downloading...
From: https://drive.google.com/uc?id=1j7x8xhMimKbvW62D-XeDfuRyj9ia636q
To: /content/valid.csv
100%|██████████| 3.32M/3.32M [00:00<00:00, 38.1MB/s]

File downloaded as: valid.csv

<ipython-input-1-56e9332c1738>:30: DtypeWarning: Columns (13,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('train.csv')

,SalesID,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand,saledate,...,Undercarriage_Pad_Width,Stick_Length,Thumb,Pattern_Changer,Grouser_Type,Backhoe_Mounting,Blade_Type,Travel_Controls,Differential_Type,Steering_Controls
0,1139246,66000,999089,3157,121,3.0,2004,68.0,Low,11/16/2006 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
1,1139248,57000,117657,77,121,3.0,1996,4640.0,Low,3/26/2004 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Standard,Conventional
2,1139249,10000,434808,7009,121,3.0,2001,2838.0,High,2/26/2004 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1139251,38500,1026470,332,121,3.0,2001,3486.0,High,5/19/2011 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1139253,11000,1057373,17311,121,3.0,2007,722.0,Medium,7/23/2009 0:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_valid = pd.read_csv('valid.csv')
df_valid.head()

In [ ]:
df.info()

In [26]:
# prompt: Для всех котигориальных столбцов напечатать value_counts

categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
  print(f"Value counts for column '{col}':")
  print(df[col].value_counts())
  print()

Value counts for column 'UsageBand':
UsageBand
Medium    33985
Low       23620
High      12034
Name: count, dtype: int64

Value counts for column 'saledate':
saledate
2/16/2009 0:00    1932
2/15/2011 0:00    1352
2/19/2008 0:00    1300
2/15/2010 0:00    1219
2/11/2008 0:00    1100
                  ...
1/16/2004 0:00       1
3/27/2006 0:00       1
7/25/2003 0:00       1
1/16/2006 0:00       1
6/9/2008 0:00        1
Name: count, Length: 3919, dtype: int64

Value counts for column 'fiModelDesc':
fiModelDesc
310G        5039
416C        4869
580K        4315
310E        4233
140G        4083
            ...
EX210-5        1
KX025          1
EX120-5F       1
EX100-5E       1
HW180          1
Name: count, Length: 4999, dtype: int64

Value counts for column 'fiBaseModel':
fiBaseModel
580      19798
310      17354
D6       13110
416      12687
D5        9342
         ...
830-2        1
272          1
PC230        1
KBD65        1
HW180        1
Name: count, Length: 1950, dtype: int64

Value counts for column 'fiSecondaryDesc':
fiSecondaryDesc
C       43235
B       39203
G       36424
H       24050
E       21048
        ...
LD          1
LC7A        1
SF          1
PG          1
NLC         1
Name: count, Length: 175, dtype: int64

Value counts for column 'fiModelSeries':
fiModelSeries
II           13202
LC            8936
III           5238
-1            4591
-2            3340
             ...
H                1
VI               1
-5F              1
-5A              1
FASTRRACK        1
Name: count, Length: 128, dtype: int64

Value counts for column 'fiModelDescriptor':
fiModelDescriptor
L       15875
LGP     15558
LC      12750
XL       6434
6        2885
        ...
XD          1
3L          1
K5          1
XLVP        1
TK          1
Name: count, Length: 139, dtype: int64

Value counts for column 'ProductSize':
ProductSize
Medium            62274
Large / Medium    49678
Small             26494
Mini              24840
Large             20975
Compact            6089
Name: count, dtype: int64

Value counts for column 'fiProductClassDesc':
fiProductClassDesc
Backhoe Loader - 14.0 to 15.0 Ft Standard Digging Depth             56166
Track Type Tractor, Dozer - 20.0 to 75.0 Horsepower                 17788
Wheel Loader - 150.0 to 175.0 Horsepower                            15114
Track Type Tractor, Dozer - 85.0 to 105.0 Horsepower                14731
Hydraulic Excavator, Track - 21.0 to 24.0 Metric Tons               13323
                                                                    ...
Hydraulic Excavator, Track - Unidentified (Compact Construction)       38
Wheel Loader - 1000.0 + Horsepower                                     25
Hydraulic Excavator, Track - 150.0 to 300.0 Metric Tons                21
Hydraulic Excavator, Track - 300.0 + Metric Tons                        1
Motorgrader - Unidentified                                              1
Name: count, Length: 74, dtype: int64

Value counts for column 'state':
state
Florida           63944
Texas             51682
California        29019
Washington        15955
Georgia           14309
Maryland          12965
Mississippi       12961
Ohio              12190
Colorado          11254
Illinois          11209
New Jersey        10882
North Carolina    10404
Tennessee         10027
Alabama            9997
Pennsylvania       9941
South Carolina     9794
Arizona            9173
New York           8604
Connecticut        8128
Minnesota          7734
Missouri           6961
Nevada             6693
Louisiana          6450
Kentucky           5278
Maine              5095
Indiana            4086
Arkansas           3869
New Mexico         3529
Utah               2895
Unspecified        2801
New Hampshire      2724
Wisconsin          2668
Virginia           2288
Idaho              2018
Oregon             1775
Michigan           1763
Wyoming            1662
Montana            1327
Oklahoma           1311
Iowa               1215
West Virginia       746
Nebraska            722
Kansas              659
Delaware            509
Alaska              430
North Dakota        410
Massachusetts       328
Vermont             300
South Dakota        203
Hawaii              118
Rhode Island         82
Puerto Rico          36
Washington DC         2
Name: count, dtype: int64

Value counts for column 'ProductGroup':
ProductGroup
TEX    101167
TTT     80520
BL      79415
WL      71046
SSL     43488
MG      25489
Name: count, dtype: int64

Value counts for column 'ProductGroupDesc':
ProductGroupDesc
Track Excavators       101167
Track Type Tractors     80520
Backhoe Loaders         79415
Wheel Loader            71046
Skid Steer Loaders      43488
Motor Graders           25489
Name: count, dtype: int64

Value counts for column 'Drive_System':
Drive_System
Two Wheel Drive     46139
Four Wheel Drive    32996
No                  24428
All Wheel Drive       798
Name: count, dtype: int64

Value counts for column 'Enclosure':
Enclosure
OROPS                  173932
EROPS                  139026
EROPS w AC              87820
EROPS AC                   17
NO ROPS                     3
None or Unspecified         2
Name: count, dtype: int64

Value counts for column 'Forks':
Forks
None or Unspecified    178300
Yes                     13777
Name: count, dtype: int64

Value counts for column 'Pad_Type':
Pad_Type
None or Unspecified    70614
Reversible              5832
Street                  2663
Grouser                   25
Name: count, dtype: int64

Value counts for column 'Ride_Control':
Ride_Control
No                     77685
None or Unspecified    63116
Yes                     7805
Name: count, dtype: int64

Value counts for column 'Stick':
Stick
Standard    48829
Extended    30305
Name: count, dtype: int64

Value counts for column 'Transmission':
Transmission
Standard               140328
None or Unspecified     23147
Powershift              11731
Powershuttle             4244
Hydrostatic              3204
Direct Drive              418
Autoshift                 114
AutoShift                  44
Name: count, dtype: int64

Value counts for column 'Turbocharged':
Turbocharged
None or Unspecified    75211
Yes                     3923
Name: count, dtype: int64

Value counts for column 'Blade_Extension':
Blade_Extension
None or Unspecified    24692
Yes                      527
Name: count, dtype: int64

Value counts for column 'Blade_Width':
Blade_Width
14'                    9615
None or Unspecified    9283
12'                    4968
16'                     933
13'                     329
<12'                     91
Name: count, dtype: int64

Value counts for column 'Enclosure_Type':
Enclosure_Type
None or Unspecified    21923
Low Profile             2510
High Profile             786
Name: count, dtype: int64

Value counts for column 'Engine_Horsepower':
Engine_Horsepower
No          23937
Variable     1282
Name: count, dtype: int64

Value counts for column 'Hydraulics':
Hydraulics
2 Valve                141404
Standard               104423
Auxiliary               40737
Base + 1 Function       24770
3 Valve                  5622
4 Valve                  2960
Base + 3 Function         299
Base + 2 Function         127
Base + 5 Function          89
Base + 4 Function          76
Base + 6 Function          53
None or Unspecified        10
Name: count, dtype: int64

Value counts for column 'Pushblock':
Pushblock
None or Unspecified    19463
Yes                     5756
Name: count, dtype: int64

Value counts for column 'Ripper':
Ripper
None or Unspecified    83452
Yes                     7902
Multi Shank             7633
Single Shank            5150
Name: count, dtype: int64

Value counts for column 'Scarifier':
Scarifier
None or Unspecified    12719
Yes                    12511
Name: count, dtype: int64

Value counts for column 'Tip_Control':
Tip_Control
None or Unspecified    16207
Sideshift & Tip         7070
Tip                     1942
Name: count, dtype: int64

Value counts for column 'Tire_Size':
Tire_Size
None or Unspecified    46339
20.5                   15242
14"                     8813
23.5                    8480
26.5                    4482
17.5                    3932
29.5                    2704
17.5"                   1793
13"                      766
20.5"                    718
15.5                     607
15.5"                    457
23.5"                    302
7.0"                      52
23.1"                     20
10"                        8
10 inch                    3
Name: count, dtype: int64

Value counts for column 'Coupler':
Coupler
None or Unspecified    184582
Manual                  23301
Hydraulic                6069
Name: count, dtype: int64

Value counts for column 'Coupler_System':
Coupler_System
None or Unspecified    40430
Yes                     3028
Name: count, dtype: int64

Value counts for column 'Grouser_Tracks':
Grouser_Tracks
None or Unspecified    40515
Yes                     2847
Name: count, dtype: int64

Value counts for column 'Hydraulics_Flow':
Hydraulics_Flow
Standard               42784
High Flow                553
None or Unspecified       25
Name: count, dtype: int64

Value counts for column 'Track_Type':
Track_Type
Steel     84880
Rubber    14273
Name: count, dtype: int64

Value counts for column 'Undercarriage_Pad_Width':
Undercarriage_Pad_Width
None or Unspecified    79651
32 inch                 5213
28 inch                 3114
24 inch                 2962
20 inch                 2652
30 inch                 1592
36 inch                 1519
18 inch                 1429
34 inch                  531
16 inch                  460
31 inch                  184
27 inch                  143
22 inch                  133
26 inch                   97
33 inch                   91
14 inch                   49
15 inch                   33
25 inch                   17
31.5 inch                  2
Name: count, dtype: int64

Value counts for column 'Stick_Length':
Stick_Length
None or Unspecified    78820
9' 6"                   5765
10' 6"                  3456
11' 0"                  1577
9' 10"                  1439
9' 8"                   1434
9' 7"                   1401
12' 10"                 1066
10' 2"                   983
8' 6"                    901
8' 2"                    606
10' 10"                  404
12' 8"                   317
11' 10"                  299
8' 4"                    271
8' 10"                   103
9' 5"                    101
12' 4"                    97
15' 9"                    84
6' 3"                     50
13' 7"                    10
14' 1"                     7
13' 9"                     7
13' 10"                    6
19' 8"                     5
7' 10"                     3
15' 4"                     3
24' 3"                     2
9' 2"                      1
Name: count, dtype: int64

Value counts for column 'Thumb':
Thumb
None or Unspecified    83093
Manual                  9358
Hydraulic               6837
Name: count, dtype: int64

Value counts for column 'Pattern_Changer':
Pattern_Changer
None or Unspecified    90255
Yes                     8898
No                        65
Name: count, dtype: int64

Value counts for column 'Grouser_Type':
Grouser_Type
Double    84653
Triple    14498
Single        2
Name: count, dtype: int64

Value counts for column 'Backhoe_Mounting':
Backhoe_Mounting
None or Unspecified    78652
Yes                       20
Name: count, dtype: int64

Value counts for column 'Blade_Type':
Blade_Type
PAT                    38612
Straight               13323
None or Unspecified    11431
Semi U                  8617
VPAT                    3547
U                       1862
Angle                   1662
No                       743
Landfill                  25
Coal                      11
Name: count, dtype: int64

Value counts for column 'Travel_Controls':
Travel_Controls
None or Unspecified    69923
Differential Steer      4879
Finger Tip              2624
2 Pedal                 1142
Lever                    840
Pedal                    416
1 Speed                   10
Name: count, dtype: int64

Value counts for column 'Differential_Type':
Differential_Type
Standard        68073
Limited Slip     1130
No Spin           206
Locking             2
Name: count, dtype: int64

Value counts for column 'Steering_Controls':
Steering_Controls
Conventional           68679
Command Control          537
Four Wheel Standard      138
Wheel                     14
No                         1
Name: count, dtype: int64

In [ ]:
df.describe()

In [ ]:
df.UsageBand.value_counts()

In [ ]:
df['UsageBand_2'] = df['UsageBand'].map({'Low': 1, 'Medium': 2, 'High': 3})
df.head()

In [ ]:
# meen coding for fiModelDesc
# Create a dictionary to map fiModelDesc values to their mean values
mean_values = df.groupby('fiModelDesc')['SalePrice'].mean().to_dict()
# Replace fiModelDesc values with their mean values
df['fiModelDesc_2'] = df['fiModelDesc'].map(mean_values)

df.head()

In [18]:
# the most simple and most aggressive and dumb data processing
df2 = df.select_dtypes('number')  # drop all categorical variables
df2 = df2.dropna()  # drop all rows with missing values
df2 = df2.set_index('SalesID')
df2

,SalePrice,MachineID,ModelID,datasource,auctioneerID,YearMade,MachineHoursCurrentMeter,UsageBand_2,fiModelDesc_2
SalesID,,,,,,,,,
1139246,66000,999089,3157,121,3.0,2004,68.0,1.0,46081.730769
1139248,57000,117657,77,121,3.0,1996,4640.0,1.0,55499.064371
1139249,10000,434808,7009,121,3.0,2001,2838.0,3.0,12437.068966
1139251,38500,1026470,332,121,3.0,2001,3486.0,3.0,31495.714286
1139253,11000,1057373,17311,121,3.0,2007,722.0,2.0,11038.404908
...,...,...,...,...,...,...,...,...,...
6319998,55000,1831997,5864,149,16.0,1999,24.0,1.0,44508.219178
6320871,15200,1827657,18266,149,0.0,2006,24.0,1.0,15210.000000
6321495,11200,1925538,18648,149,99.0,1000,2196.0,1.0,17232.258065
6321692,13000,1920012,18588,149,99.0,2008,24.0,1.0,13265.151515
6331198,30700,1867348,20316,149,0.0,2005,1120.0,1.0,28340.000000

In [19]:
X = df2.drop(columns='SalePrice')
y = df2['SalePrice']

X_small = X.sample(20000)
y_small = y.loc[X_small.index]

X_train, X_test, y_train, y_test = train_test_split(X_small, y_small, test_size=0.3, random_state=42)

In [20]:
%%time

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

def RMSE(y, y_pred):
    return np.sqrt(mean_squared_error(y, y_pred))

print(f'Train RMSE:', RMSE(y_train, y_train_pred))
print(f'Test RMSE:', RMSE(y_test, y_test_pred))

Train RMSE: 3743.379206231142
Test RMSE: 9842.151455889727
CPU times: user 8.74 s, sys: 2.81 ms, total: 8.74 s
Wall time: 8.85 s

In [23]:
X.MachineID.nunique(), X.auctioneerID.nunique()

(60552, 30)

In [24]:
%%time

X2 = X_small.drop(columns=['MachineID'])
X_train, X_test, y_train, y_test = train_test_split(X2, y_small, test_size=0.3, random_state=42)

model = RandomForestRegressor()
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

def RMSE(y, y_pred):
    return np.sqrt(mean_squared_error(y, y_pred))

print(f'Train RMSE:', RMSE(y_train, y_train_pred))
print(f'Test RMSE:', RMSE(y_test, y_test_pred))

Train RMSE: 3760.1239464306695
Test RMSE: 9767.054721812301
CPU times: user 7.14 s, sys: 7.48 ms, total: 7.14 s
Wall time: 8.2 s

In [25]:
X_valid = df_valid.set_index('SalesID')[X2.columns]

# the dumbest null handling possible - fill with mean value
for col in X_valid.columns:
    X_valid[col] = X_valid[col].fillna(X_valid[col].mean())

y_valid_pred = model.predict(X_valid)
y_valid_pred = pd.Series(y_valid_pred, index=X_valid.index, name='SalePrice')
y_valid_pred

KeyError: "['UsageBand_2', 'fiModelDesc_2'] not in index"

In [ ]:
from datetime import datetime

f'submission_{datetime.now().isoformat()}'
y_valid_pred.to_csv(f'submission_{datetime.now().isoformat()}.csv')

In [ ]:
### Feature importance
pd.Series(
    model.feature_importances_,
    index=model.feature_names_in_
).sort_values(ascending=False)

ModelID                     0.635940
YearMade                    0.188489
MachineHoursCurrentMeter    0.107432
auctioneerID                0.034715
datasource                  0.033423
dtype: float64